# Generated by Django 6.0.7 on 2026-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('ideas', 'Ideas'), ('urgent', 'Urgent'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
